outfit418_backup_ratting/urls.py
from django.urls import path

from . import views

app_name = 'outfit418backup'


urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('audit/', views.audit, name='audit'),
    path('find_jeremy/', views.find_jeremy, name='find_jeremy'),
    path('event_backups/', views.event_backup, name='event_backups'),
    path('event_backups/restore/<int:event_id>/', views.restore_event, name='restore_event'),
]

outfit418_backup_ratting/templates/outfit418_backup_ratting/audit.html
{% extends 'allianceauth/base-bs5.html' %}
{% load outfit_tags %}

{% block page_title %}418 Audit{% endblock page_title %}

{% block extra_css %}
    {% include "bundles/datatables-css-bs5.html" %}
    <link rel="stylesheet" type="text/css" href="{% allianceauth_pve_static 'allianceauth_pve/css/spop.css' %}">
    <link rel="stylesheet" type="text/css" href="{% allianceauth_pve_static 'allianceauth_pve/css/copy_text.css' %}">
{% endblock %}

{% block content %}
    <div class="col-lg-12" style="padding: 10px 10px 10px 10px">
        <table class="table table-aa">
            <thead>
                <tr>
                    <th>Main</th>
                    <th>Characters</th>
                    <th>Last login (ET)</th>
                </tr>
            </thead>
            <tbody>
                {% for main in mains %}
                    <tr>
                        <td><span class="copy-text">{{ main.character.character_name }}</span></td>
                        <td>
                            {% for char in main.character.character_ownership.user.chars %}
                                <span class="badge {% if char.character|ct_is_active %}text-bg-primary{% else %}text-bg-danger{% endif %} copy-text" data-bs-toggle="tooltip" data-bs-title="Last login (ET): {{ char.last_login|date:"Y/m/d H:i" }}">{{ char.character.character_name }}</span>
                            {% endfor %}
                        </td>
                        <td>
                            <span class="badge {% if main.is_updating %}text-bg-primary{% else %}text-bg-danger{% endif %}" data-bs-toggle="tooltip" data-bs-title="Older update between all chars: {% if main.older_last_update %}{{ main.older_last_update|date:"Y/m/d H:i" }}{% else %}Never{% endif %}">{{ main.last_login|date:"Y/m/d H:i" }}</span>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

{% block extra_javascript %}
    {% include "bundles/datatables-js-bs5.html" %}
    <script src="{% allianceauth_pve_static 'allianceauth_pve/js/spop.js' %}"></script>
    <script src="{% allianceauth_pve_static 'allianceauth_pve/js/copy_text.js' %}"></script>
{% endblock extra_javascript %}

{% block extra_script %}
    $(document).ready(function() {
        $('[data-bs-toggle="tooltip"]').tooltip();
        $('.table').DataTable({
            "pageLength": 50
        });
    });
{% endblock extra_script %}

outfit418_backup_ratting/templates/outfit418_backup_ratting/event_backups.html
{% extends 'allianceauth/base-bs5.html' %}


{% block extra_css %}
    {% include "bundles/datatables-css-bs5.html" %}
{% endblock %}

{% block content %}
    <div class="col-lg-12" style="padding: 10px 10px 10px 10px">
        <table class="table table-aa">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Start</th>
                    <th>User</th>
                    <th>Deleted On</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for event_backup in events %}
                    <tr>
                        <td>{{ event_backup.title }}</td>
                        <td>{{ event_backup.start_time }}</td>
                        <td>{{ event_backup.user }}</td>
                        <td>{{ event_backup.deleted_on }}</td>
                        <td><a href="{% url "outfit418backup:restore_event" event_backup.pk %}" class="btn btn-success">Restore</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

{% block extra_javascript %}
    {% include "bundles/datatables-js-bs5.html" %}
{% endblock extra_javascript %}

{% block extra_script %}
    $(document).ready(function() {
        $('.table').DataTable({
            "pageLength": 50
        });
    });
{% endblock extra_script %}

outfit418_backup_ratting/templates/outfit418_backup_ratting/find_jeremy.html
{% extends 'allianceauth/base-bs5.html' %}

{% block page_title %}Find Jeremy{% endblock page_title %}

{% block extra_css %}
    {% include "bundles/datatables-css-bs5.html" %}
{% endblock %}

{% block content %}
    <div class="col-lg-12" style="padding: 10px 10px 10px 10px">
        <table class="table table-aa">
            <thead>
                <tr>
                    <th>Character</th>
                    <th>Ships</th>
                </tr>
            </thead>
            <tbody>
                {% for char, names in jeremy_owners.items %}
                    <tr>
                        <td>{{ char.character_name }}</td>
                        <td>
                            {% for name in names %}
                                <span>{{ name }},</span>
                            {% endfor %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

{% block extra_javascript %}
    {% include "bundles/datatables-js-bs5.html" %}
{% endblock extra_javascript %}

{% block extra_script %}
    $(document).ready(function() {
        $('.table').DataTable({
            "pageLength": 50
        });
    });
{% endblock extra_script %}

outfit418_backup_ratting/templates/outfit418_backup_ratting/index.html
{% extends 'allianceauth/base-bs5.html' %}
{% load django_bootstrap5 %}

{% block page_title %}Backup 418 Ratting{% endblock page_title %}


{% block content %}
    <div class="col-lg-12">
        <form method="post" enctype="multipart/form-data"> {% csrf_token %}
            <div class="form-group">
                {% bootstrap_form form %}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock content %}